[default_config]
version = "0.9.0"
assembler = "nasm"
instruction_set = "x86/x86-64"

[[project]]
path = "src/"
version = "0.9.0"
assembler = "nasm"
instruction_set = "x86/x86-64"

[project.opts]
compiler = "nasm"
compile_flags_txt = ["-f elf32"]
diagnostics = true
default_diagnostics = false
