#ifndef YUTSUOS_VGA_H
#define YUTSUOS_VGA_H

#define YUTSUOS_VGA_ADDRESS 0xB8000
#define YUTSUOS_VGA_WIDTH 80
#define YUTSUOS_VGA_HEIGHT 25
#define YUTSUOS_VGA_SIZE (YUTSUOS_VGA_WIDTH * YUTSUOS_VGA_HEIGHT)

#define YUTSUOS_VGA_DEFAULT_COLOR 0x0F
#define YUTSUOS_VGA_BLANK ' '

void yutsuos_vga_clear_screen(void);

#endif /* YUTSUOS_VGA_H */
